### ISSUE TITLE
http method in ex. 07

### ISSUE THREAD

**Issue by olaven** [arcuri82/web_development_and_api_design#7]
In exercise 07, it is specified that POST should be used when retrieving quizzes from the server. I may be wrong, but I thought GET would be more appropriate since we are retrieving data from the server, not sending data.

**Comment by arcuri82** [comment]
thx for creating such issue!
I added some explanation in the text of exercise 07. Let me know if that clarifies the issue

**Comment by olaven** [comment]
I believe so, thank you 😄 
Closing the issue.
